import React from 'react';
import styled from 'styled-components/native';
import { COLORS } from '@/constants/theme';
import { MOOD_CONFIG, type JournalEntry } from '@/types/models';

// ── Types ────────────────────────────────────────────────────────────────────

interface JournalCardProps {
  entry: JournalEntry;
  onPress: () => void;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function formatDate(epoch: number): string {
  const d = new Date(epoch);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

// ── Styled Components ────────────────────────────────────────────────────────

const Card = styled.Pressable`
  background-color: ${COLORS.surface1};
  border-width: 1px;
  border-color: ${COLORS.border};
  border-radius: 14px;
  padding: 16px;
  margin-bottom: 12px;
`;

const TopRow = styled.View`
  flex-direction: row;
  align-items: center;
  gap: 10px;
  margin-bottom: 10px;
`;

const MoodEmoji = styled.Text`
  font-size: 20px;
`;

const DateText = styled.Text`
  color: ${COLORS.textDim};
  font-size: 11px;
  font-weight: 500;
  letter-spacing: 0.3px;
`;

const TagsRow = styled.View`
  flex-direction: row;
  flex-wrap: wrap;
  flex: 1;
  justify-content: flex-end;
  gap: 4px;
`;

const TagChip = styled.View`
  background-color: ${COLORS.surface2};
  border-radius: 8px;
  padding: 2px 8px;
`;

const TagText = styled.Text`
  color: ${COLORS.textDim};
  font-size: 9px;
  font-weight: 600;
  letter-spacing: 0.3px;
`;

const Title = styled.Text`
  color: ${COLORS.textPrimary};
  font-size: 15px;
  font-weight: 600;
  letter-spacing: 0.3px;
  margin-bottom: 4px;
`;

const BodyPreview = styled.Text`
  color: ${COLORS.textSecondary};
  font-size: 13px;
  font-weight: 500;
  line-height: 20px;
`;

const ReflectionBadge = styled.View`
  background-color: ${COLORS.crimsonGlow};
  border-radius: 8px;
  padding: 4px 10px;
  align-self: flex-start;
  margin-top: 10px;
`;

const ReflectionBadgeText = styled.Text`
  color: ${COLORS.crimson};
  font-size: 9px;
  font-weight: 700;
  letter-spacing: 0.5px;
`;

// ── Component ────────────────────────────────────────────────────────────────

export default function JournalCard({ entry, onPress }: JournalCardProps) {
  const mood = MOOD_CONFIG[entry.mood];

  return (
    <Card onPress={onPress}>
      <TopRow>
        <MoodEmoji>{mood.emoji}</MoodEmoji>
        <DateText>{formatDate(entry.date)}</DateText>
        <TagsRow>
          {entry.tags.slice(0, 3).map((tag) => (
            <TagChip key={tag}>
              <TagText>#{tag}</TagText>
            </TagChip>
          ))}
        </TagsRow>
      </TopRow>

      <Title numberOfLines={1}>{entry.title}</Title>
      <BodyPreview numberOfLines={2}>{entry.body}</BodyPreview>

      {entry.isAutoGenerated && (
        <ReflectionBadge>
          <ReflectionBadgeText>From reflection</ReflectionBadgeText>
        </ReflectionBadge>
      )}
    </Card>
  );
}
