// ──────────────────────────────────────────────
// The Reflector – AI Context Builder
// ──────────────────────────────────────────────
// Reads ALL stores and compresses data into token-efficient
// payloads for Gemini. This is the AI's memory.

import { useReflectorStore } from '@/store/useReflectorStore';
import { useJournalStore } from '@/store/useJournalStore';
import { useDisciplineStore } from '@/store/useDisciplineStore';
import { useFocusStore } from '@/store/useFocusStore';
import { useGamificationStore } from '@/store/useGamificationStore';

const MS_PER_DAY = 86_400_000;

// ── Types ────────────────────────────────────────────────────────────────────

export interface AIGridSummary {
  routineTitle: string;
  dayIndex: number;
  totalDays: number;
  completedDays: number;
  lapsedDays: number;
  pendingDays: number;
  streakInGrid: number;
  isHardResetEnabled: boolean;
}

export interface AILapseSummary {
  date: number;
  routineName: string;
  dayIndex: number;
  failureReason: string;
}

export interface AIJournalSummary {
  date: number;
  title: string;
  body: string;
  mood: string;
  tags: string[];
  isAutoGenerated: boolean;
}

export interface AIDisciplineSummary {
  date: number;
  score: number;
  breakdown: Record<string, number>;
}

export interface AIFocusSummary {
  date: number;
  durationMinutes: number;
  type: string;
  completed: boolean;
}

export interface AINiyyahSummary {
  routineTitle: string;
  why: string;
  sacrifice: string;
  reward: string;
  signedName: string;
}

export interface AITodoSummary {
  title: string;
  completed: boolean;
  category: string;
  priority: string;
}

export interface AIFullContext {
  // Identity
  currentStreak: number;
  longestStreak: number;
  level: number;
  totalXP: number;
  totalDaysCompleted: number;
  totalGridsCompleted: number;
  totalGridsFailed: number;
  totalFocusMinutes: number;
  totalJournalEntries: number;
  
  // Wounds
  totalMisses: number;
  activeWounds: number;
  healedWounds: number;
  
  // Active grids
  activeGrids: AIGridSummary[];
  
  // Recent lapses (last 7 days)
  recentLapses: AILapseSummary[];
  
  // Recent journal entries (last 7 days)
  recentJournals: AIJournalSummary[];
  
  // Recent discipline scores (last 7 days)
  recentDiscipline: AIDisciplineSummary[];
  disciplineTrend: 'improving' | 'declining' | 'stable';
  averageScore7d: number;
  
  // Recent focus sessions (last 7 days)
  recentFocus: AIFocusSummary[];
  todayFocusMinutes: number;
  weekFocusMinutes: number;
  
  // Active Niyyahs
  activeNiyyahs: AINiyyahSummary[];
  
  // Today's todos
  todayTodos: AITodoSummary[];
  todayTodosCompleted: number;
  todayTodosTotal: number;
}

// ── Builders ─────────────────────────────────────────────────────────────────

function getTodayStart(): number {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  return d.getTime();
}

function getGridStreak(days: { status: string }[]): number {
  let streak = 0;
  // Count backwards from latest completed day
  for (let i = days.length - 1; i >= 0; i--) {
    if (days[i].status === 'completed') streak++;
    else if (days[i].status === 'scarred') break;
    // 'pending' days are future, skip them
  }
  return streak;
}

function calculateTrend(scores: number[]): 'improving' | 'declining' | 'stable' {
  if (scores.length < 3) return 'stable';
  const firstHalf = scores.slice(0, Math.floor(scores.length / 2));
  const secondHalf = scores.slice(Math.floor(scores.length / 2));
  const avgFirst = firstHalf.reduce((a, b) => a + b, 0) / firstHalf.length;
  const avgSecond = secondHalf.reduce((a, b) => a + b, 0) / secondHalf.length;
  const diff = avgSecond - avgFirst;
  if (diff > 5) return 'improving';
  if (diff < -5) return 'declining';
  return 'stable';
}

/**
 * Build the full AI context from all stores.
 * This is the AI's complete knowledge of the user.
 */
export function buildFullContext(): AIFullContext {
  const todayStart = getTodayStart();
  const weekAgoMs = todayStart - 7 * MS_PER_DAY;
  
  const reflector = useReflectorStore.getState();
  const journal = useJournalStore.getState();
  const discipline = useDisciplineStore.getState();
  const focus = useFocusStore.getState();
  const gamification = useGamificationStore.getState();
  
  // Active grids
  const activeGrids: AIGridSummary[] = reflector.grids
    .filter(g => g.status === 'active')
    .map(g => {
      const routine = reflector.routines.find(r => r.id === g.routineId);
      const completed = g.days.filter(d => d.status === 'completed').length;
      const lapsed = g.days.filter(d => d.status === 'scarred').length;
      const pending = g.days.filter(d => d.status === 'pending').length;
      const currentDay = g.days.findIndex(d => d.date >= todayStart) + 1 || g.days.length;
      return {
        routineTitle: routine?.title ?? 'Unknown',
        dayIndex: currentDay,
        totalDays: g.days.length,
        completedDays: completed,
        lapsedDays: lapsed,
        pendingDays: pending,
        streakInGrid: getGridStreak(g.days),
        isHardResetEnabled: g.isHardResetEnabled,
      };
    });
    
  // Recent lapses
  const recentLapses: AILapseSummary[] = reflector.grids
    .filter(g => g.status === 'active')
    .flatMap(g => {
      const routine = reflector.routines.find(r => r.id === g.routineId);
      return g.days
        .filter(d => d.status === 'scarred' && d.date >= weekAgoMs)
        .map(d => ({
          date: d.date,
          routineName: routine?.title ?? 'Unknown',
          dayIndex: d.dayIndex,
          failureReason: d.failureReason ?? '',
        }));
    });

  // Recent journals
  const recentJournals: AIJournalSummary[] = journal.journalEntries
    .filter(e => e.date >= weekAgoMs)
    .map(e => ({
      date: e.date,
      title: e.title,
      body: e.body.slice(0, 400), // Token cap
      mood: e.mood,
      tags: e.tags,
      isAutoGenerated: e.isAutoGenerated,
    }));

  // Recent discipline
  const recentDiscipline: AIDisciplineSummary[] = discipline.snapshots
    .filter(s => s.date >= weekAgoMs)
    .map(s => ({
      date: s.date,
      score: s.score,
      breakdown: s.breakdown as unknown as Record<string, number>,
    }));
  
  const scores = recentDiscipline.map(d => d.score);
  const averageScore7d = scores.length > 0
    ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length)
    : 0;

  // Recent focus
  const recentFocus: AIFocusSummary[] = focus.focusSessions
    .filter(s => s.startTime >= weekAgoMs)
    .map(s => ({
      date: s.startTime,
      durationMinutes: Math.round(s.actualDuration / 60000),
      type: s.type,
      completed: s.completed,
    }));

  // Active Niyyahs
  const activeNiyyahs: AINiyyahSummary[] = reflector.pacts
    .filter(p => {
      const grid = reflector.grids.find(g => g.id === p.gridId);
      return grid?.status === 'active';
    })
    .map(p => {
      const grid = reflector.grids.find(g => g.id === p.gridId);
      const routine = grid ? reflector.routines.find(r => r.id === grid.routineId) : undefined;
      return {
        routineTitle: routine?.title ?? 'Unknown',
        why: p.why,
        sacrifice: p.sacrifice,
        reward: p.reward,
        signedName: p.signedName,
      };
    });

  // Today's todos
  const todayTodos: AITodoSummary[] = reflector.dailyTodos
    .filter(t => t.date === todayStart)
    .map(t => ({
      title: t.title,
      completed: t.completed,
      category: t.category,
      priority: t.priority,
    }));

  return {
    currentStreak: gamification.userStats.currentStreak,
    longestStreak: gamification.userStats.longestEverStreak,
    level: gamification.userStats.level,
    totalXP: gamification.userStats.totalXP,
    totalDaysCompleted: gamification.userStats.totalDaysCompleted,
    totalGridsCompleted: gamification.userStats.totalGridsCompleted,
    totalGridsFailed: gamification.userStats.totalGridsFailed,
    totalFocusMinutes: gamification.userStats.totalFocusMinutes,
    totalJournalEntries: gamification.userStats.totalJournalEntries,
    totalMisses: gamification.wounds.totalMisses,
    activeWounds: gamification.wounds.activeWounds,
    healedWounds: gamification.wounds.healedWounds,
    activeGrids,
    recentLapses,
    recentJournals,
    recentDiscipline,
    disciplineTrend: calculateTrend(scores),
    averageScore7d,
    recentFocus,
    todayFocusMinutes: focus.getTodayFocusMinutes(),
    weekFocusMinutes: focus.getWeekFocusMinutes(),
    activeNiyyahs,
    todayTodos,
    todayTodosCompleted: todayTodos.filter(t => t.completed).length,
    todayTodosTotal: todayTodos.length,
  };
}

/**
 * Compress the full context into a token-efficient string for Gemini.
 */
export function compressContext(ctx: AIFullContext): string {
  const lines: string[] = [];
  
  // Identity
  lines.push(`=== USER PROFILE ===`);
  lines.push(`Level ${ctx.level} | ${ctx.totalXP} XP | Streak: ${ctx.currentStreak}d (best: ${ctx.longestStreak}d)`);
  lines.push(`Completed: ${ctx.totalDaysCompleted} days, ${ctx.totalGridsCompleted} grids | Failed: ${ctx.totalGridsFailed} grids`);
  lines.push(`Focus: ${ctx.totalFocusMinutes} min lifetime | Journals: ${ctx.totalJournalEntries}`);
  lines.push(`Wounds: ${ctx.activeWounds} active, ${ctx.healedWounds} healed, ${ctx.totalMisses} total misses`);
  
  // Active grids
  if (ctx.activeGrids.length > 0) {
    lines.push(`\n=== ACTIVE ROUTINES ===`);
    for (const g of ctx.activeGrids) {
      lines.push(`• "${g.routineTitle}" Day ${g.dayIndex}/${g.totalDays} | ✓${g.completedDays} ✗${g.lapsedDays} | streak=${g.streakInGrid} | hardReset=${g.isHardResetEnabled}`);
    }
  }
  
  // Niyyahs
  if (ctx.activeNiyyahs.length > 0) {
    lines.push(`\n=== NIYYAH (INTENTIONS) ===`);
    for (const n of ctx.activeNiyyahs) {
      lines.push(`• "${n.routineTitle}" — Why: "${n.why}" | Sacrifice: "${n.sacrifice}" | Reward: "${n.reward}"`);
    }
  }
  
  // Recent lapses
  if (ctx.recentLapses.length > 0) {
    lines.push(`\n=== RECENT LAPSES (7d) ===`);
    for (const l of ctx.recentLapses) {
      const dateStr = new Date(l.date).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
      lines.push(`• ${dateStr} — "${l.routineName}" Day ${l.dayIndex} — Reason: "${l.failureReason || 'none given'}"`);
    }
  }
  
  // Discipline scores
  if (ctx.recentDiscipline.length > 0) {
    lines.push(`\n=== DISCIPLINE SCORES (7d) === avg=${ctx.averageScore7d} trend=${ctx.disciplineTrend}`);
    for (const d of ctx.recentDiscipline) {
      const dateStr = new Date(d.date).toLocaleDateString('en-US', { weekday: 'short' });
      const breakdown = Object.entries(d.breakdown).map(([k, v]) => `${k}=${v}`).join(', ');
      lines.push(`• ${dateStr}: ${d.score} (${breakdown})`);
    }
  }
  
  // Recent journals
  if (ctx.recentJournals.length > 0) {
    lines.push(`\n=== JOURNAL ENTRIES (7d) ===`);
    for (const j of ctx.recentJournals) {
      const dateStr = new Date(j.date).toLocaleDateString('en-US', { weekday: 'short' });
      lines.push(`• ${dateStr} [${j.mood}]${j.isAutoGenerated ? ' (auto)' : ''}: "${j.body.slice(0, 200)}"`);
    }
  }
  
  // Focus sessions
  if (ctx.recentFocus.length > 0) {
    lines.push(`\n=== FOCUS SESSIONS (7d) === today=${ctx.todayFocusMinutes}min week=${ctx.weekFocusMinutes}min`);
    for (const f of ctx.recentFocus) {
      const dateStr = new Date(f.date).toLocaleDateString('en-US', { weekday: 'short' });
      lines.push(`• ${dateStr}: ${f.durationMinutes}min ${f.type} ${f.completed ? '✓' : '✗'}`);
    }
  }
  
  // Today's todos
  if (ctx.todayTodosTotal > 0) {
    lines.push(`\n=== TODAY'S TASKS === ${ctx.todayTodosCompleted}/${ctx.todayTodosTotal} done`);
    for (const t of ctx.todayTodos) {
      lines.push(`• [${t.completed ? 'x' : ' '}] ${t.title} (${t.category}/${t.priority})`);
    }
  }
  
  return lines.join('\n');
}

/**
 * Build a lightweight context for the home greeting (fast, fewer tokens).
 */
export function buildHomeContext(): string {
  const ctx = buildFullContext();
  const lines: string[] = [];
  
  const now = new Date();
  const hour = now.getHours();
  const timeOfDay = hour < 12 ? 'morning' : hour < 17 ? 'afternoon' : 'evening';
  
  lines.push(`Time: ${timeOfDay}`);
  lines.push(`Streak: ${ctx.currentStreak}d | Level: ${ctx.level}`);
  
  if (ctx.activeGrids.length > 0) {
    const g = ctx.activeGrids[0];
    lines.push(`Primary routine: "${g.routineTitle}" Day ${g.dayIndex}/${g.totalDays} (✓${g.completedDays} ✗${g.lapsedDays})`);
  }
  
  if (ctx.recentLapses.length > 0) {
    lines.push(`Recent lapses: ${ctx.recentLapses.length} in last 7 days`);
  }
  
  lines.push(`Discipline avg: ${ctx.averageScore7d} (${ctx.disciplineTrend})`);
  lines.push(`Focus today: ${ctx.todayFocusMinutes}min | Tasks: ${ctx.todayTodosCompleted}/${ctx.todayTodosTotal}`);
  
  return lines.join('\n');
}

/**
 * Build a lapse-specific context for the reckoning screen.
 */
export function buildLapseContext(failureReason: string, routineName: string, dayIndex: number): string {
  const ctx = buildFullContext();
  const lines: string[] = [];
  
  lines.push(`=== CURRENT LAPSE ===`);
  lines.push(`Routine: "${routineName}" Day ${dayIndex}`);
  lines.push(`Reason: "${failureReason}"`);
  
  // Find similar past lapses
  const similarLapses = ctx.recentLapses.filter(l => l.routineName === routineName);
  if (similarLapses.length > 1) {
    lines.push(`\nThis routine has been lapsed ${similarLapses.length} times in the last 7 days.`);
    const reasons = similarLapses.map(l => l.failureReason).filter(Boolean);
    if (reasons.length > 0) {
      lines.push(`Previous reasons: ${reasons.join(' | ')}`);
    }
  }
  
  // Add Niyyah for this routine
  const niyyah = ctx.activeNiyyahs.find(n => n.routineTitle === routineName);
  if (niyyah) {
    lines.push(`\nTheir Niyyah for this routine: "${niyyah.why}"`);
    lines.push(`Sacrifice: "${niyyah.sacrifice}"`);
  }
  
  lines.push(`\nOverall: Streak=${ctx.currentStreak}d, Level=${ctx.level}, Active wounds=${ctx.activeWounds}`);
  
  return lines.join('\n');
}
