// ──────────────────────────────────────────────
// The Reflector – The Oracle
// ──────────────────────────────────────────────
// Passive AI entity that delivers a weekly verdict.
// Fetches from the Gemini backend, caches per week.
// Never crashes the app — returns null on failure.

import AsyncStorage from '@react-native-async-storage/async-storage';
import { api } from '@/lib/apiClient';
import { useAuthStore } from '@/store/useAuthStore';
import { useJournalStore } from '@/store/useJournalStore';
import { useDisciplineStore } from '@/store/useDisciplineStore';
import { useGamificationStore } from '@/store/useGamificationStore';

// ── Constants ────────────────────────────────────────────────────────────────

const CACHE_KEY = 'reflector-oracle-verdict';
const MS_PER_DAY = 86_400_000;

// ── Types ────────────────────────────────────────────────────────────────────

interface AnalysisResponse {
  patterns: string[];
  insights: string[];
  recommendations: string[];
  risk_level: string;
  summary: string;
}

interface CachedVerdict {
  weekKey: string;
  verdict: string;
  fetchedAt: number;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Get the Monday timestamp for a given date (used as cache key) */
function getMondayOfWeek(date: Date = new Date()): number {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  const day = d.getDay();
  // Sunday=0 → offset is 6, Monday=1 → offset is 0, etc.
  const diff = day === 0 ? 6 : day - 1;
  d.setDate(d.getDate() - diff);
  return d.getTime();
}

/** Get the week key string for caching */
function getWeekKey(date: Date = new Date()): string {
  return `week-${getMondayOfWeek(date)}`;
}

// ── Main Function ────────────────────────────────────────────────────────────

/**
 * Fetch the Oracle's verdict for the current week.
 * Returns a single brutal paragraph, or null if unavailable.
 *
 * - Checks AsyncStorage cache first (keyed by week's Monday)
 * - If not cached, gathers data and calls the backend
 * - Returns null if user is not logged in or API fails
 * - Never throws — all errors are swallowed gracefully
 */
export async function fetchOracleVerdict(): Promise<string | null> {
  try {
    // 1. Check auth state — Oracle requires login
    const { isLoggedIn } = useAuthStore.getState();
    if (!isLoggedIn) return null;

    // 2. Check cache
    const weekKey = getWeekKey();
    const cached = await getCachedVerdict();
    if (cached && cached.weekKey === weekKey) {
      return cached.verdict;
    }

    // 3. Gather data from stores
    const payload = buildPayload();
    if (!payload) return null;

    // 4. Call the backend
    const response = await api<AnalysisResponse>('/analyze/journal', {
      method: 'POST',
      body: payload,
    });

    // 5. Compose the verdict from the response
    const verdict = composeVerdict(response);
    if (!verdict) return null;

    // 6. Cache it
    await cacheVerdict(weekKey, verdict);

    return verdict;
  } catch {
    // Never crash the app. The Oracle simply stays silent.
    return null;
  }
}

/**
 * Get cached verdict without making an API call.
 * Used by the home screen teaser to avoid network requests.
 */
export async function getCachedOracleVerdict(): Promise<string | null> {
  try {
    const weekKey = getWeekKey();
    const cached = await getCachedVerdict();
    if (cached && cached.weekKey === weekKey) {
      return cached.verdict;
    }
    return null;
  } catch {
    return null;
  }
}

// ── Internal Helpers ─────────────────────────────────────────────────────────

async function getCachedVerdict(): Promise<CachedVerdict | null> {
  try {
    const raw = await AsyncStorage.getItem(CACHE_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as CachedVerdict;
  } catch {
    return null;
  }
}

async function cacheVerdict(weekKey: string, verdict: string): Promise<void> {
  try {
    const cached: CachedVerdict = {
      weekKey,
      verdict,
      fetchedAt: Date.now(),
    };
    await AsyncStorage.setItem(CACHE_KEY, JSON.stringify(cached));
  } catch {
    // Caching failure is non-critical
  }
}

function buildPayload(): {
  journal_entries: object[];
  discipline_snapshots: object[];
  wound_tracker: object;
} | null {
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  const todayMs = now.getTime();
  const weekAgoMs = todayMs - 7 * MS_PER_DAY;

  // Journal entries — last 7 days, compressed
  const allEntries = useJournalStore.getState().journalEntries;
  const recentEntries = allEntries
    .filter((e) => e.date >= weekAgoMs)
    .map((e) => ({
      date: e.date,
      title: e.title,
      body: e.body.slice(0, 500), // Token-efficient: cap at 500 chars
      mood: e.mood,
      tags: e.tags,
      isAutoGenerated: e.isAutoGenerated,
    }));

  // Discipline snapshots — last 7 days
  const allSnapshots = useDisciplineStore.getState().snapshots;
  const recentSnapshots = allSnapshots
    .filter((s) => s.date >= weekAgoMs)
    .map((s) => ({
      date: s.date,
      score: s.score,
      breakdown: s.breakdown,
    }));

  // Wound tracker
  const wounds = useGamificationStore.getState().wounds;

  // If no data at all, no point calling the API
  if (recentEntries.length === 0 && recentSnapshots.length === 0) {
    return null;
  }

  return {
    journal_entries: recentEntries,
    discipline_snapshots: recentSnapshots,
    wound_tracker: {
      totalMisses: wounds.totalMisses,
      activeWounds: wounds.activeWounds,
      healedWounds: wounds.healedWounds,
      perfectDayStreak: wounds.perfectDayStreak,
    },
  };
}

function composeVerdict(response: AnalysisResponse): string | null {
  // The Oracle delivers a single, brutal paragraph.
  // Priority: summary first, then first insight, then first pattern.
  const parts: string[] = [];

  if (response.summary) {
    parts.push(response.summary);
  }

  // Append the most cutting insight
  if (response.insights && response.insights.length > 0) {
    parts.push(response.insights[0]);
  }

  // If risk is high, append a warning
  if (response.risk_level === 'high' && response.recommendations?.length > 0) {
    parts.push(response.recommendations[0]);
  }

  if (parts.length === 0) return null;

  return parts.join(' ');
}
